# MotdManager Configuration file!
# @author syamn <admin@sakura-server.net>
# github: https://github.com/syamn/MotdManager

#==================#
#   Basic Config   #
#==================#
# sending MOTD list
MotdList:
- '&cThis is default MOTD!'

# if use show fake max players count feature, change this to numeric
FakeMaxPlayer: disable

#==================#
#   Debug Config   #
#==================#
Debug: false

#==================#
#   DO NOT TOUCH   #
#==================#
# Do not touch this option! It is a check if you are running the recent configuration version
DontTouchThisConfig: 1.0